Edit contact
cmgoersch/capstone-project pull request #14
Opened 2023-05-19 12:54 UTC by cmgoersch

Update works. I am curious about comments.

Best regards,
Calle

2023-05-19 14:01 UTC, ThomasF85 requested changes
Looks good, but please check out my comments!

2023-05-21 23:11 UTC, cmgoersch commented on components/RandomFunction.js
>    const handleRandomFriendClick = () => {
I hope I have understood your request for improvement correctly... 
Thank you for your efforts and accuracy.
Greetings and good start of the week

2023-05-21 23:12 UTC, cmgoersch commented
I hope for release to continue hacking with full energy

2023-05-22 08:21 UTC, cmgoersch commented on components/Picture/ProfilePictureChange.js
> +import m27 from "../../public/monster/m27.png";
I put the images, since they are static, in "Public". Somehow I have to import them :)

2023-05-22 08:26 UTC, doctype-Melvin commented on pages/contacts/[id].js
> +  // const friend = state.find((element) => element.id == idPath[0]);
If you're code doesn't use this, just remove it.

2023-05-22 08:53 UTC, merged